#!/usr/bin/env python2

import sys
import os
import time
import tempfile
import shutil
import libtorrent

USAGE = """
magnet2torrent - translate a magnet link to a torrent file and save it to disk

usage:  magnet2torrent [magnet link] [download path]
"""

def read_config(config_file):
	config = {}

	with open(config_file,'r') as f:
		raw = f.read()

	for line in raw.split('\n'):
		parts = line.slip(' = ')
		config[parts[0]] = parts[1]

	return config

if __name__ == '__main__':
	try:
		config_file = os.path.join(os.environ['XDG_CONFIG_HOME'], 'magnet2torrentrc')
	except KeyError:
		config_file = os.path.join(os.environ['HOME'], '.config/magnet2torrentrc')
	else:
		config_file = None

	try:
		magnet = sys.argv[1]
		try:
			path = sys.argv[2]
		except IndexError:
			path = os.getcwd()
	except IndexError:
		print(USAGE)	
		sys.exit(1)

	temp_dir = tempfile.mkdtemp(prefix='magnet2torrent')

	session = libtorrent.session()
	handle = session.add_torrent({'save_path':temp_dir, 'url':magnet})
	
	done = False

	while (not done):
		try:
			info = handle.get_torrent_info()
			done = True
		except RuntimeError:
			time.sleep(1)

	torrent = libtorrent.create_torrent(info)
	data = libtorrent.bencode(torrent.generate())

	file_name = '%s/%s.torrent' % (path, info.name())
	with open(file_name, 'wb') as f:
		f.write(data)

	shutil.rmtree(temp_dir)